export const ERROR_STATE = 'ERROR_STATE'
export const CONTEXT = 'CONTEXT'
export const PERSON = 'PERSON'
export const LOGINSTATE = 'LOGINSTATE'
export const SIDEBAR = 'SIDEBAR'
export const HEADERMESSAGE = 'HEADERMESSAGE'
export const LIST = 'LIST'
